export const HalloweenFlags = {
    Flags : {
        Elder     : (1 << 0),
        Kiai      : (1 << 1),
        Werewolf  : (1 << 2),
        Graveyard : (1 << 3),
        Chapel    : (1 << 4),
        Lenka     : (1 << 5),
        WitchHut  : (1 << 6),
        Jenna     : (1 << 7),
        Broomfuck : (1 << 8),
        PatchesPW : (1 << 9),
        Carepack  : (1 << 10),
        Laggoth   : (1 << 11),
        Mausoleum : (1 << 12),
        TRoom     : (1 << 13),
        NadirMa   : (1 << 14),
    },
    Ronnie : {
        NotMet  : 0,
        Removed : 1,
        PCBeta  : 2,
        PCAlpha : 3,
    },
    Harthon : {
        Met          : (1 << 0),
        Thrall       : (1 << 1),
        ThrallCalled : (1 << 2),
        Feminized    : (1 << 3),
        BJ           : (1 << 4),
    },
    NadirMa : {
        GaveCock  : (1 << 0),
        GaveBalls : (1 << 1),
        SaidNo    : (1 << 2),
    },
};
